### ISSUE TITLE
Upgrade to eslint 0.20.0

### ISSUE THREAD

**Issue by TheAxeMan301** [cyaninc/beaker#26]
I wouldn't expect any major issues.

**Comment by job13er** [comment]
I'm gonna be making some enhancements to our `eslint` w.r.t. React later today or tomorrow. I'll bump the version to the latest as well.

**Comment by TheAxeMan301** [comment]
Cool. http-server also has 0.8.0. There is probably not much difference in either but if you have -g installed them you need to uninstall them and downgrade since they are peerDependencies of beaker.
