### ISSUE TITLE
Gruntfile override fails

### ISSUE THREAD

**Issue by TheAxeMan301** [cyaninc/beaker#29]
The default Gruntfile invites you to customize and gives you some example code that tweaks the eslint configuration. But if you actually uncomment it then you get an error!

Loading "Gruntfile.js" tasks...ERROR
>> TypeError: Object #<Object> has no method 'replace'

The error happens on the set() call.

**Comment by TheAxeMan301** [comment]
It looks like the set call just needs another argument:

   grunt.config.set('eslint', eslintConfig);

**Comment by job13er** [comment]
Sorry @TheAxeMan301 We don't use those project-templates, we have our own for our projects, and those lines were out of date. I'm updating them right now.

**Comment by job13er** [comment]
Version 2.2.2 published with the fix.
