### ISSUE TITLE
Make http-sync optional

### ISSUE THREAD

**Issue by TheAxeMan301** [cyaninc/beaker#44]
Could we get http-sync changed to an optionalDependency? This will simplify and speed up the setup process for those of us who don't need the github hooks. The github hook could detect the missing package and print a helpful message.

Noticed that there may be some changes to http-sync in store for io.js/0.12 compatibility and if that will solve this problem then great.

**Comment by job13er** [comment]
`http-sync` will likely be removed when we switch to `io.js`

**Comment by job13er** [comment]
`execSync` will also be removed, further speeding up installs.

**Comment by job13er** [comment]
@TheAxeMan301 I'm working on converting our CLI to use all async utilities, so this should be able to be removed before switching to `iojs`
