### ISSUE TITLE
Missing project dependencies for initial demo

### ISSUE THREAD

**Issue by garrickajo** [cyaninc/beaker#67]
After ``npm i beaker`` & running ``grunt``, the following screenshot shows the error saying missing jquery and bootstrap

![grunt_err_ss](https://cloud.githubusercontent.com/assets/2825366/8142406/7c4f8e14-1130-11e5-89e2-e9aa15cdda58.png)

This was solved locally with ``npm i jquery --save``...

As I'm not sure what the demo intentions and which package config it ran (I thought webpack one, but jquery was in there), I thought it would not be fitting to do a PR.

Looks fun! Thanks!

**Comment by job13er** [comment]
@garrickajo Can you clarify what steps you took? You just ran raw `grunt` on a fresh directory after installing `beaker`? I'm not sure how that would work, there would be no top-level `Gruntfile.js`. Did you use `beaker` to create a new project? Maybe with `beaker --init`? If that's the case, after the initialization you need to do a `make install` to install the dependencies before running `grunt`.

**Comment by job13er** [comment]
`beaker` by itself doesn't have a `demo/` directory, so I'm guessing you did a `beaker init` somewhere.

**Comment by job13er** [comment]
The [project template](https://github.com/cyaninc/beaker/blob/master/files/project-templates/webpack/package.json) for a new `webpack` project has `jquery` as a dependency and `bootstrap` as a devDependency, so `make install` should get both of those installed for you.

**Comment by garrickajo** [comment]
Sorry, @job13er - it was written in a bit of haste. I'm talking about from the npm side, creating a project directory and installing beaker from npm, and running default grunt task, ie. web-server.

Steps
```
mkdir projdir
cd projdir
 npm install beaker
 ./node_modules/.bin/beaker newConfig
 ./node_modules/.bin/beaker init --type webpack
 grunt
```

Works after:
```
npm i jquery --save
npm i bootstrap --save
grunt
```

I suspect it's missing those libs in a package.json somewhere.

I looked in the source for package.json, and it seems like one of them in files/project-templates is missing jquery and bootstrap in dependencies, but I haven't built from source yet, so I can't confirm.

Let me know, if you need more info.

**Comment by garrickajo** [comment]
@job13er - I ran ``make install`` in the project directory and it ran without problem. Thanks Adam. I didn't see that instruction  in the README.
